### ISSUE TITLE
Display image cropper when using basic file selector

### ISSUE THREAD

**Issue by dutchigor** [joppuyo/acf-image-aspect-ratio-crop#11]
There is an issue when a user does not have access to the media library but can create posts with a field group with an Image Aspect Ratio Crop field. 
When such a user creates a post, ACF skips the media library and simply provides a default file selector for the image field. In this case the cropper is skipped and it is not possible to save the image.

Could it be possible to add the image cropper in this scenario and allow the saving and cropping for these users?

**Comment by joppuyo** [comment]
Hey, is this a backend form or a frontend form?

I’m not very familiar with WP permission system would you be able to post steps to reproduce so I can see if I can figure out a fix.

**Comment by dutchigor** [comment]
Hi, Sorry for the late reply. I missed your comment somehow.

I am using this on a front end form but it is also reproducible on the back end. Actually, in the process of getting the steps to reproduce I found that this might be a bigger issue: currently, neihter contributers, subscribers nor guests are able to use the cropper field, either in the front or back end.

You can reproduce this as follows:
1. Create a new field group with an "Image Aspect Ratio Crop" field and show this field if Post type = Post
2. Create a new user with contributer rights
3. log in as the new user
4. Create a new post and try to add an image in the image crop field.

Note that the cropping modal does not display, the image is just added as is.

**Comment by joppuyo** [comment]
Fixed in v5.0.0
