### ISSUE TITLE
PHP 8.1 / WP 6.2 deprecation notices

### ISSUE THREAD

**Issue by GerritChan** [joppuyo/acf-image-aspect-ratio-crop#128]
Hi, 

I am getting the following deprecation notices on PHP 8.1 when activating the cropping plugin. 

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in \web\wp\wp-includes\functions.php on line 7053

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in \web\wp\wp-includes\functions.php on line 2165

**Comment by joppuyo** [comment]
Hey!

Thanks for reporting this issue. I will try to look into this during this week to see if there’s a way to fix these warnings.

**Comment by joppuyo** [comment]
Apologies for the delays but I haven't had time to look into this yet. However, I have reserved some time next week to do the necessary updates so the plugin works properly with latest PHP and WordPress versions.

**Comment by joppuyo** [comment]
I've released version 6.0.3 of the plugin today which should fix these issues.

**Comment by GerritChan** [comment]
Issue is fixed. Thanks alot!
