### ISSUE TITLE
Critical error Wordpress REST API after adding Image Aspect Ratio Crop Field

### ISSUE THREAD

**Issue by mkruip05** [joppuyo/acf-image-aspect-ratio-crop#133]
Hi there, 

I am receiving a critical error after I add the Image Aspect Ratio Crop Field. I want the field to be displayed through the REST API. Sadly it is not working for me.

![Screenshot 2023-07-04 at 10 47 59](https://github.com/joppuyo/acf-image-aspect-ratio-crop/assets/23746262/0a5e9f86-3657-4bf8-b813-0d94a64a8456)

I enabled the checkbox "REST API compatibility mode", but that didn't made any difference.

![Screenshot 2023-07-04 at 10 52 53](https://github.com/joppuyo/acf-image-aspect-ratio-crop/assets/23746262/62877847-2e8a-4e96-93da-33c82d651ff7)

Would love to hear a solution for this issue.

**Comment by joppuyo** [comment]
Hey! Could you check the server logs and copy and paste any error messages you see below? Other option is to enable WP_DEBUG in wp-config.php which should display more useful errors than "There Has Been a Critical Error on Your Website".

**Comment by joppuyo** [comment]
This is very likely same issue as #130
