### ISSUE TITLE
Woocommerce

### ISSUE THREAD

**Issue by tomekwebdeveloper** [joppuyo/acf-image-aspect-ratio-crop#17]
Is it possible to use it in a woocommerce? In product page with add to cart?

**Comment by joppuyo** [comment]
Hey!

This plugin works fine with WooCommerce. You can add a field group to Product post type with an aspect ratio crop field and then access it in your product template using ACF's template functions: https://www.advancedcustomfields.com/resources/displaying-custom-field-values-in-your-theme/

**Comment by tomekwebdeveloper** [comment]
thanks for the answer. Is it possible to integrate, for example, the field from the width and height?

**Comment by joppuyo** [comment]
I'm not entirely sure what you mean by integrating with and hight.

Unfortunately, I can't answer support request about ACF itself. This plugin works just like the standard, built-in ACF image field, but it is restricted to certain aspect ratio.

I suggest you try the normal image field first and see if you can accomplish your task. It's easy to replace the standard image field with this add-on if you require the images to be in certain aspect ratio.

ACF has good support [documentation](https://www.advancedcustomfields.com/resources/) on their site. And if you have ACF specific questions, you can try asking on their [support forum](https://support.advancedcustomfields.com/topics/).

I hope I was able to help.

**Comment by tomekwebdeveloper** [comment]
Ok, thanks for the explanation. So I probably need a standard image field. In general, it was about the possibility of this movie. How do you think is possible that using ACF?

https://drive.google.com/file/d/1rXULZVyRI8_itTVK3d8D_KssWCa_tyqy/view

**Comment by joppuyo** [comment]
Hey,

Unfortunately this sort of functionality is not supported with this plugin as it only works on the WordPress admin and not in WooCommerce checkout.

I would look into creating custom functionality using the same library that I use for cropping and integrate it into the checkout workflow. https://fengyuanchen.github.io/cropperjs/
