### ISSUE TITLE
Hiding sale category from shop page

### ISSUE THREAD

**Issue by kimhawleydesign** [joppuyo/acf-image-aspect-ratio-crop#18]
Hello! I am trying to hide the sale category from my shop page. I have tried adding the code below to functions.php (from this page: https://docs.woocommerce.com/document/exclude-a-category-from-the-shop-page/), but it hasn't worked for me so far. Am I missing something?

/**
 * Exclude products from a particular category on the shop page
 */
function custom_pre_get_posts_query( $q ) {

    $tax_query = (array) $q->get( 'tax_query' );

    $tax_query[] = array(
           'taxonomy' => 'product_cat',
           'field' => 'slug',
           'terms' => array( 'sale' ), // Don't display products in the sale category on the shop page.
           'operator' => 'NOT IN'
    );

    $q->set( 'tax_query', $tax_query );

}
add_action( 'woocommerce_product_query', 'custom_pre_get_posts_query' );

**Comment by joppuyo** [comment]
Hi!

I’m not sure what this has to do with this plugin (ACF Image Aspect Ratio Crop). The code you linked will hide products on a page and has nothing to do with images.

I suggest you open an issue on WooCommerce support forum: https://wordpress.org/support/plugin/woocommerce/

**Comment by kimhawleydesign** [comment]
Thank you! I just opened an issue on the WooCommerce support forum. So sorry I posted this here. I'm new to GitHub. I appreciate the link!
