### ISSUE TITLE
Do "Width" and "Height" settings have to be required?

### ISSUE THREAD

**Issue by phildittrich** [joppuyo/acf-image-aspect-ratio-crop#22]
With version 3.2 the "Width" and "Height" settings became required. Before that I used the plugin for aspect cropping and also just for image fields with a cropping option. I achieved that by not using the width and height options. Is there a special reason they are required now?

I would propose to have a third crop type option: "Free cropping" which just gives the user the cropping window without any predefined crop ratio. The width and height options could be hidden when that option is choosen.

Please let me know what you think about that. I could also start a pull request.

Cheers!
Phil

**Comment by joppuyo** [comment]
Hey,

You can see my previous reply to this question here: https://wordpress.org/support/topic/free-cropping/

So basically not specifying values was never an intended feature.

But if there are at least 2 people who used the plugin this way, it could be added as a feature.

If you want you could create a PR for this functionality.

**Comment by phildittrich** [comment]
Hey joppuyo!

I thought so - always fun to see things like that getting a feature :-)

I've put together a pull request and hope you are fine with it.

Thanks for the great plugin!

**Comment by annelyse** [comment]
@joppuyo 
A free crop option would be awesome !

**Comment by joppuyo** [comment]
Hey @annelyse , an option for free crop has been added in the latest plugin version. Could you check that it works like expected so this issue may be closed.

Thanks!

**Comment by annelyse** [comment]
@joppuyo you are awesome !!! Thanks a lot ! 
I will do that !

**Comment by annelyse** [comment]
@joppuyo hey, I made a test. 
After added the field in free mode, I saved it and the free crop seems to work well. 
But if I come back to the Acf fields administration and edit it, after the second save, there is a javascript error, and I can't save my fields anymore, unless if I remove the free mode option. 
the error : 
An invalid form control with name='acf_fields[23193][aspect_ratio_height]' is not focusable.

**Comment by joppuyo** [comment]
Hey @annelyse , could you tell me which operating system and browser you are using? WordPress and ACF versions would be also useful to know.

Thanks!

**Comment by annelyse** [comment]
I'm on Macbook Pro 
Chrome : Version 81.0.4044.138 (Build officiel) (64 bits)
WordPress : 5.2.6
Acf Pro : 5.8.11

I don't know if I was clear before, maybe in a video is more clear ;) [https://www.loom.com/share/c5740350b3684a86b7ef4d68c60190ac](url)

**Comment by joppuyo** [comment]
Hey @annelyse , thanks for your recording, it made the issue clear for me.

I just released version v3.3.1 which should fix this issue. Could you check that it's been corrected?

Thanks!

**Comment by joppuyo** [comment]
Closing since free crop feature has been implemented. Please open another issue if there are other problems related to the feature.
