### ISSUE TITLE
Theme integration

### ISSUE THREAD

**Issue by sebalzert** [joppuyo/acf-image-aspect-ratio-crop#26]
Both acf and acf-extended offer the possibility to integrate them in a theme. Is there a proper way of doing this with acf-image-aspect-ratio-crop as well? I know about the pros and cons of doing so in general but for my usecase it would be big benefit. 
Thank you in advance :)

**Comment by joppuyo** [comment]
Hey,

I have never included plugins in a theme so it's a bit hard to say.

Maybe you could try to include the plugin file `acf-image-aspect-ratio-crop.php` in your theme and see if it works?

Another option might be using something like [TGMP Plugin Activation](http://tgmpluginactivation.com/) which should support including plugins with themes out of the box.

**Comment by joppuyo** [comment]
I'm closing this once since there's a workaround using the plugin previously mentioned.
