### ISSUE TITLE
"original_image" is blank if crop is same as original image

### ISSUE THREAD

**Issue by rdundon** [joppuyo/acf-image-aspect-ratio-crop#28]
Not sure if this is an issue, but just making a note here if it's not expected behavior.

_BTW to start, this is a great plugin! It's super-useful to have crops tied to an image. I worked with another CMS (Blox) and that was very useful._

I am using this for a set of thumbnail images (which use the cropped version) that, when clicked, show a larger image (the original version) in a lightbox.

I currently access the thumbnail by (variable name replaced for simplicity):
 `$work_example['image']['sizes']['medium']`

And the original / larger version of the image by:
 `$image_aspect_ratio_field['original_image']['url']`

There was one case where an thumbnail image did not need to be cropped from the original / larger image. In that case, 'original_image' was null, and the lightbox didn't work.

Cropping the image just by a few pixels caused 'original_image' to not be null, so I'm assuming it's only populated when a crop different from the original image is made.

**Comment by joppuyo** [comment]
Hey, good observation. In my view the current behavior is correct. It doesn't make sense to have `original_image` key if there is no original image.

I think this can be solved on the theme level with simple conditional

```php
$original_image_url = $image_aspect_ratio_field['url']
if ($image_aspect_ratio_field['original_image']) {
    $original_image_url = $image_aspect_ratio_field['original_image']['url']
}
