### ISSUE TITLE
re-editing crop opens modal full window height and buttons are not visible

### ISSUE THREAD

**Issue by codemonkeynorth** [joppuyo/acf-image-aspect-ratio-crop#29]
Hi,

we updated to Version 3.3.1 

when we go to re-edit the crop, the modal dialog opens up full window height and the buttons are off screen (and can't be scrolled since it's fixed)

- crop is set 1440x500
- the image in the cropper is 800x277.7
- the rest is filled with a checkerboard background outside of the crop handles
- however the modal content dimensions are now 800x969 (`<div class="cropper-drag-box cropper-crop cropper-modal" data-cropper-action="crop"></div>`).. whereas for new images the modal content is eg 800x533

thanks
J

**Comment by joppuyo** [comment]
Hey, would it be possible to post a screenshot showing this issue?

I would also be interested in:

* What WordPress version you are using?
* What ACF version you are using?
* What browser you are using?

Thanks!

**Comment by codemonkeynorth** [comment]
Hi,

sorry. just discovered for some reason it appears to be a PHP warning being output at the top of the page that's somehow breaking it...
https://github.com/acf-extended/ACF-Extended/issues/48

if you have a way to ignore that it would be great but I guess it's affecting the page render since the error appears before the opening doctype

```
<br />
<b>Notice</b>:  Trying to access array offset on value of type bool in <b>/nas/content/live/devkeele/wp-content/plugins/acf-extended/includes/modules/dev.php</b> on line <b>512</b><br />
<!DOCTYPE html>
```

I've turned `WP_DEBUG` off for now

(PS Wordpress 5.4.2, Latest ACF Pro, Chrome - but probably not relevant in this case due to above)

thanks
J

**Comment by codemonkeynorth** [comment]
screenshot anyway...
![cropper](https://user-images.githubusercontent.com/20189985/86468243-e5d04b80-bd2e-11ea-9798-fc17e5a1d7bb.png)

**Comment by joppuyo** [comment]
Ok, good thing you found out the cause for the issue.

Unfortunately there’s not much I can do if there is some text outputted to the page where it shouldn’t. I hope ACF Extended will be able to solve this issue soon.
