### ISSUE TITLE
GraphQL problem

### ISSUE THREAD

**Issue by igorbumba** [joppuyo/acf-image-aspect-ratio-crop#30]
Doesn't have option for GraphQL. All other fields from ACF currently support GraphQL.

**Comment by joppuyo** [comment]
Hey, I'll have to check if it's possible to add this on my plugin's side or if this is something that needs to be added on GraphQL plugin side. You are talking about [this plugin](https://github.com/wp-graphql/wp-graphql-acf), right?

It looks like there are some filters that can be used but they are not documented super well.

**Comment by igorbumba** [comment]
Yes, that's the plugin. We found out a hackie/workaround version but still didn't test it.

**Comment by joppuyo** [comment]
Hey, I figured it out and added GraphQL support in the latest version, please check it out and see if it works like it should.

**Comment by igorbumba** [comment]
It works. You are awesome! Thank you!

**Comment by yantei** [comment]
Looks like it is not working in current versions - field appears in schema but always returns null

**Comment by joppuyo** [comment]
I don't use WP GraphQL but feel free to send a pull request if you figure out a way to fix this in the current version of that plugin, preferably in a backwards-compatible manner.

**Comment by yantei** [comment]
> I don't use WP GraphQL but feel free to send a pull request if you figure out a way to fix this in the current version of that plugin, preferably in a backwards-compatible manner.

you can remove this answer as I've deleted my comment - sorry, that was my fault, everything works correctly :)
