### ISSUE TITLE
Crop buttons not displaying

### ISSUE THREAD

**Issue by basil78** [joppuyo/acf-image-aspect-ratio-crop#37]
I installed the plugin on my dev site and it worked perfectly. Now I've uploaded the files to live I've got the problem that the crop buttons aren't showing.  Inspecting suggests that they're below the bottom of the screen, but I can't see how to access them 
![image](https://user-images.githubusercontent.com/35966235/96712938-c6ba0000-1397-11eb-8f2b-84daa05a789f.png)

**Comment by joppuyo** [comment]
Hey,

Please make sure there are no errors printed on the page, [see this issue](https://github.com/joppuyo/acf-image-aspect-ratio-crop/issues/29).

**Comment by basil78** [comment]
Yup, that was the problem! Thank you very much  - I missed that earlier issue when I was looking, :)
