### ISSUE TITLE
Allow using admin-ajax.php instead of REST API

### ISSUE THREAD

**Issue by joppuyo** [joppuyo/acf-image-aspect-ratio-crop#38]
There's at least one bug report that cropping REST API endpoint returns 403 error.

Maybe we should add an option to allow using admin-ajax.php instead of REST API for those users having issues.

**Comment by tim9192** [comment]
+1

I had a problem on my multisite with a Multilingual Press installation.
When I try to edit a page, it breaks my backend. After a downgrade to version 4.1.4 it works like a charm.

Warning:
array_intersect_key(): Expected parameter 1 to be an array, string given in 
/homepages/27/*********/htdocs/kunden/test/wp-includes/rest-api/class-wp-rest-server.php

Warning:
Cannot modify header information - headers already sent by (output started at /homepages/27/********/htdocs/kunden/test/wp-includes/rest-api/class-wp-rest-server.php:1402) 

Great plugin by the way :)
Greetings.

**Comment by PaulvanMoorsel** [comment]
Same issue as @tim9192 here after updating to Wordpress 5.6. Great plugin!

**Comment by joppuyo** [comment]
Hey,

Thanks for the bug report.

I always check compatibility with new WordPress versions as soon as possible after release, it's been only four days so please bear with me 🙂 . 

I'm working on a fix right now to solve the warning ´array_intersect_key(): Expected parameter 1 to be an array, string given´

I'll release a new version when it's fixed.

Thanks

**Comment by joppuyo** [comment]
I just released version v5.0.4 which contains a fix for this issue, could you confirm that it's fixed?

Thank you!

**Comment by PaulvanMoorsel** [comment]
Thank you very much for the quick action, I just tested and can confirm it's fixed!

**Comment by joppuyo** [comment]
Great, good to know!

I'm still leaving this issue open as the issue with WordPress 5.6 is not strictly related to the original issue.

**Comment by joppuyo** [comment]
I'm closing this issue since the problem described in the original post has been fixed in v5.0.4.
