### ISSUE TITLE
Cropping is not working after the update

### ISSUE THREAD

**Issue by devtest8** [joppuyo/acf-image-aspect-ratio-crop#40]
Hello,

After the last updates when i try to crop, I receive the error: Failed to crop image
On the console i see the another error:
/wp-json/aiarc/v1/crop:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by joppuyo** [comment]
Hey,

Thank you for the error report. 500 (Internal Server Error) is a very general error and it's hard to say what causes it.

Can you check the server error log for any error messages?

Thanks.

**Comment by devtest8** [comment]
The another error screenshot:

![4a4hc5S 1](https://user-images.githubusercontent.com/55086500/100937793-a045c380-3504-11eb-8c31-6adc21c42fa5.png)

**Comment by devtest8** [comment]
Probably the 500 issue is related to 404 error:

GET /wp-json/aiarc/v1/get/3800 404 (Not Found)

**Comment by joppuyo** [comment]
I think there could be an issue with the REST API in your WordPress installation. I have received a bug report about this and I'm planning on adding a compatibility mode to use admin-ajax.php as in 4.x.x . 

Could you check the WordPress Site Health, it's located in Tools -> Site Health.

Check if you have any errors regarding the REST API.

**Comment by joppuyo** [comment]
Could you also check that attachment with id 12361 exists?

**Comment by devtest8** [comment]
This is a multi-site installation.
There is no problems on Site Health and the attachment is exist (i have selected it from the gallery to crop).
No server errors are detected.

**Comment by devtest8** [comment]
When i manually open in browser /wp-json/aiarc/v1/crop , i got this:

{"code":"rest_no_route","message":"\u041f\u043e\u0434\u0445\u043e\u0434\u044f\u0449\u0438\u0439 \u043c\u0430\u0440\u0448\u0440\u0443\u0442 \u0434\u043b\u044f URL \u0438 \u043c\u0435\u0442\u043e\u0434\u0430 \u0437\u0430\u043f\u0440\u043e\u0441\u0430 \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d","data":{"status":404}}

**Comment by joppuyo** [comment]
If this is multisite in a subfolder, I think there might be an issue in the code that causes the plugin to call the REST API in the parent page. I will debug and fix this tomorrow.

**Comment by joppuyo** [comment]
I jsut released new version v5.0.3, could you check that it fixes the problem? @devtest8

**Comment by devtest8** [comment]
Yes, it is working now. Thank you very much

**Comment by manoj382** [comment]
Still happening for me on 5.1.2. Any fix??

**Comment by dannydamnboy** [comment]
Hi there it's happening again, in version Version 5.1.4

wp-json/aiarc/v1/crop is returning 404: '"No route was found matching the URL and request method."

**Comment by brinman** [comment]
I'm having this issue as well, but only with one particular image. I get a bunch of JSON when visiting my domain/wp-json.

**Comment by brinman** [comment]
> I'm having this issue as well, but only with one particular image. I get a bunch of JSON when visiting my domain/wp-json.

For others who may be experiencing this, it appears to be some kind of mal-formed jpg file.  I just opened the original image in photoshop and re-saved using "save for web" and then uploaded it to wordpress.  Then the cropping worked fine.

**Comment by yCodeTech** [comment]
This happened to to me on a valet for windows with a laravel and bedrock wp setup on windows 10 with php 7.4.
One of the comments here said to "check the WordPress Site Health", I noticed in mine under the "One or more recommended modules are missing" tab, it said GD and Imagick was missing or disabled. After installing GD by uncommenting the `extension=gd2` in my php.ini (C:Somefolder/php7.4/php.ini) in my standalone php installation, and upon restarting my valet to reinit the localhost server, the issue is then fixed.

So it's worth double checking the wp site health and also checking the php info with `phpinfo()` on the site.
