### ISSUE TITLE
Fail to crop

### ISSUE THREAD

**Issue by cbernard** [joppuyo/acf-image-aspect-ratio-crop#48]
Hello,

I have an issue with the last version of the plugin 5.0.5 - I'm always getting an error "fail to crop" when I'm trying to import an image through the wordpress back-end. I'm using the last version of local by flywheel on mac OS Big sur.

Checking the JS console gave me this. "https://eau-de-lavey.local/wp-json/aiarc/v1/crop 40"
![Capture d’écran 2021-01-21 à 17 16 32](https://user-images.githubusercontent.com/1035981/105329746-73608380-5c0c-11eb-9c94-70555866b9d5.png)

I found a related topic here : https://wordpress.org/support/topic/failed-to-crop/ but couldn't solve it.

Downgraded to 4.1.4 and everything's fine now !

Tks

**Comment by cbernard** [comment]
Found the solution : I'm actually using https://github.com/roots/soil and so the REST API was disabled.

**Comment by joppuyo** [comment]
Hey, glad you found a way to fix this issue. Version 5 and later does require REST API to function. Maybe I will need to add more explicit notice about this in the plugin readme.
