### ISSUE TITLE
Max File Size not working reliably

### ISSUE THREAD

**Issue by chrispink** [joppuyo/acf-image-aspect-ratio-crop#69]
I haven't totally fathomed the logic of the issue but it's something along the lines of

Maximum File Size :

Fractional MB sizes do not allow uploads of any sizes
Integer MB sizes work but not accurately and rather defeats the object which is to give a non-technical person access to cropping

I will do some more local testing and see if I can better establish the logic.

**Comment by joppuyo** [comment]
Hey,

Are you using the field in the WordPress admin or as a front-end form?

Could you also check if you can reproduce this issue with the stock ACF image field? This field is largely based on that.

**Comment by chrispink** [comment]
I’m not sure at the moment, I’m having trouble confirming the issue. I think maybe I’ll mark it as closed (or ‘one of those weird things’)

Thanks for responding.

**Comment by chrispink** [comment]
I haven't been able to consistently reproduce this issue.
