### ISSUE TITLE
Internal Server Error 500 - /aiarc/v1/crop

### ISSUE THREAD

**Issue by codyng** [joppuyo/acf-image-aspect-ratio-crop#77]
I was using 5.1.4 and Microsoft Azure Storage for WordPress latest version (4.3.2).
It failed to crop and console.log showed the 500 server error from the /aiarc/v1/crop API endpoint.

However, it worked fine without using the Azure external storage plugin.

Are there any problems of the API call between those external storage and the API itself?

How to fix the problem?

<img width="978" alt="Screenshot 2021-09-24 at 18 18 40" src="https://user-images.githubusercontent.com/4618641/134715544-8db5820a-2078-4154-8a16-1b149d6c693c.png">

**Comment by joppuyo** [comment]
Could you check the server logs for an error message? That would help a lot with figuring out what’s causing this issue.

**Comment by codyng** [comment]
Hi I found that it is **NOT** the acf-image-aspect-ratio-crop problem.

The problem was from the Microsoft Azure Storage for WordPress.
