### ISSUE TITLE
Migrating from Advanced Custom Fields: Image Crop Add-on?

### ISSUE THREAD

**Issue by krishaamer** [joppuyo/acf-image-aspect-ratio-crop#97]
Hi @joppuyo thanks for your work on this plugin! I was wondering if there's any documentation on how to migrate from the  Advanced Custom Fields: Image Crop Add-on which has problem with latest PHP and WP?

Cheers,
Kris

**Comment by joppuyo** [comment]
Since this seems to be solved, I'm closing this issue.

Feel free to re-open if something comes up.
